[package]
name = "launcher"
version = "0.1.0"
authors = ["mdb"]

[dependencies]
hyper = "0.9.10"
rustc-serialize = "0.3"
rust-crypto = "0.2.36"
toml = "0.1"
zip = { version= "0.1", default-features = false }
