[command]
command = "java"
args = ["-jar", "${user_home}/.freespectro/files/b693716ddba209491d5d38741d981f64-freespectrogdx.jar"]
[command.env]
PATH = "${user_home}/.freespectro/files/jre/bin/"

[[files]]
name="original.zip"
source="https://drive.google.com/uc?export=download&id=0B4PwZlVw7EuxYlphd2lRSzJXX1E"
md5="0b838aee21937fe2c83ab524e934055c"
action="unzip"
size=5894895

[[files]]
name="custom.zip"
source="https://drive.google.com/uc?export=download&id=0B4PwZlVw7EuxWExZVEItSk5sN1U"
md5="5de58e257de677ed5f8ec74f19b0cd80"
action="unzip"
size=5922034

[[files]]
name="backgrounds.zip"
source="https://drive.google.com/uc?export=download&id=0B4PwZlVw7EuxZ2tiLWlhMERvdlU"
md5="53eb234546ef18d96c2874a7205958cc"
action="unzip"
size=1750136

[[files]]
name="freespectrogdx.jar"
source="https://github.com/illim/freespectrogdx/releases/download/v0.8/freespectrogdx.jar"
md5="b693716ddba209491d5d38741d981f64"
size=23010125

[[files]]
name="winjre.zip"
source="https://drive.google.com/uc?export=download&id=0B4PwZlVw7EuxM3kySFFWVFd3eGc"
md5="79cf8f334a78c169d2fd1093cabf215b"
action="unzip"
os="windows"
size=24578411
